schema_version: 1

context:
  version: "1.0.8"

package:
  name: rfc3161-client
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rfc3161-client/rfc3161_client-${{ version }}.tar.gz
  sha256: 4bda5a2bc6947c16b6f8df90ff0e99cb333d78ab1465517f637d313d75703651
  patches:
    - remove_openssl_vendored.patch

build:
  number: 2
  script:
    - if: win
      then: SET "OPENSSL_DIR=%LIBRARY_PREFIX%" && ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      else: OPENSSL_DIR=$PREFIX ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin
    - openssl
    - pip
    - python
  run:
    - python
    - cryptography >=43,<47

tests:
  - python:
      imports:
        - rfc3161_client
      pip_check: true

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/rfc3161-client
  repository: https://github.com/trailofbits/rfc3161-client
  documentation: https://trailofbits.github.io/rfc3161-client/
  summary: |
    rfc3161-client is a Python library implementing the Time-Stamp Protocol (TSP) described in RFC 3161.

extra:
  recipe-maintainers:
    - travishathaway
